# Generated by Django 5.0.3 on 2024-03-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('purpose', models.TextField()),
                ('highlighted', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('story', models.TextField()),
                ('highlighted', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_numbers', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('domicile', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=255)),
                ('island_name', models.CharField(max_length=255)),
                ('trip_date', models.DateField()),
                ('duration', models.TimeField()),
                ('open_registration', models.DateTimeField()),
                ('close_registration', models.DateTimeField()),
                ('objective', models.TextField()),
                ('preparation', models.TextField()),
                ('capacity', models.IntegerField()),
                ('skills', models.CharField(max_length=255)),
                ('vroles', models.CharField(max_length=255)),
                ('captain', models.IntegerField()),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_numbers', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('domicile', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htrip', models.IntegerField()),
                ('hconfirmed', models.IntegerField()),
                ('hrejected', models.IntegerField()),
                ('hcancelled', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('highlighted', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField()),
                ('unique', models.IntegerField()),
                ('cvisits', models.IntegerField()),
                ('bounce', models.FloatField()),
                ('mduration', models.TimeField()),
                ('gtu_rate', models.FloatField()),
                ('utv_rate', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blog')),
            ],
        ),
        migrations.CreateModel(
            name='UserTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phoneNum', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.TextField(blank=True, null=True)),
                ('application_status', models.CharField(choices=[('applied', 'Applied'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], max_length=50)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'unique_together': {('user', 'trip')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(through='api.UserTrip', to='api.user'),
        ),
        migrations.CreateModel(
            name='VolunteerMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_rate', models.FloatField()),
                ('completion_rate', models.FloatField()),
                ('feedback_score', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.trip')),
            ],
        ),
    ]
