# Generated by Django 4.0 on 2024-05-14 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('vision', models.TextField()),
                ('mision', models.TextField()),
                ('visited', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FundLandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_landing', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FundWriting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('isShow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('hero', 'Hero'), ('impact', 'Impact Numbers'), ('trusted_by', 'Trusted By'), ('why_join', 'Why Join Card')], default='hero', max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='homepage_videos/')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='question',
        ),
        migrations.AddField(
            model_name='blog',
            name='languange',
            field=models.CharField(choices=[('en', 'en'), ('id', 'id')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('User', 'User'), ('IO', 'Island Organizer'), ('CW', 'Content Writer')], default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='fund',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='captain',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='trip',
            name='close_registration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='duration',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='trip',
            name='island_name',
            field=models.CharField(choices=[('Sumatera', 'Sumatera'), ('Sulawesi', 'Sulawesi'), ('Kalimantan', 'Kalimantan'), ('Jawa', 'Jawa'), ('Papua', 'Papua'), ('Timor', 'Timor')], max_length=70),
        ),
        migrations.AlterField(
            model_name='trip',
            name='open_registration',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(through='api.UserTrip', to='api.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='TripQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.tripquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
