# Generated by Django 5.0.4 on 2024-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_aboutus_comment_fundlandingpage_fundwriting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_pic',
            field=models.ImageField(default='default_pic.jpg', upload_to=''),
        ),
    ]
